name: Variables demo in workflow
on: 
    push:
        branches:
            - master
env: 
    PYTHON_VERSION: 3.9
jobs: 
    build-python-code-Global:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v6
              with:
                python-version: ${{ env.PYTHON_VERSION }}
            
            - name: Print Python Version
              run: python --version
    
    build-python--code-Job:
        env:
            PYTHON_VERSION_JOB: 3.11
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup python ${{env.PYTHON_VERSION_JOB}}
              uses: actions/setup-python@v6
              with:
                python-version: ${{env.PYTHON_VERSION_JOB}}
    
    build-python-code-step:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup python ${{env.PYTHON_VERSION_STEP}}
              env:
                PYTHON_VERSION_STEP: 3.12
              uses: actions/setup-python@v6
              with: 
                python-version: ${{env.PYTHON_VERSION_STEP}}
            
            - name: Print Python Version
              run: python --version

